# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: ./cod4qol.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration:
            - Debug
            - Release
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
          name: ${{matrix.configuration}} binaries
          path: D:\a\CoD4QOL\CoD4QOL\${{matrix.configuration}}\cod4qol.asi
  upload_mod:
    runs-on: windows-latest
    steps:
      - name: Rename mod 
        run: mv D:\a\CoD4QOL\CoD4QOL\mod\cod4qol\mod.ff D:\a\CoD4QOL\CoD4QOL\mod\cod4qol\qol.ff
      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
            name: QOL FastFile
            path: D:\a\CoD4QOL\CoD4QOL\mod\cod4qol\qol.ff
